add automappers on BLL and Api layers
polashkind/InternetShop pull request #12
Opened 2023-04-07 07:27 UTC by polashkind

2023-04-07 07:48 UTC, Blackolf931 requested changes

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/BLL/Services/UserService.cs
>          public async Task<UserModel?> Create(UserEntity userEntity, CancellationToken cancellationToken)
change UserEntity to UserModel. Our service should't get entity

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/BLL/Services/UserService.cs
>          public async Task<UserModel?> Update(UserEntity userEntity, CancellationToken cancellationToken)
the same

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
>          public async Task<UserViewModel?> PostUser([FromBody] UserEntity userEntity, CancellationToken cancellationToken)
Use ChangeUserViewModel instead of UserEntity

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
>          public async Task<UserViewModel?> Update([FromBody] UserEntity userEntity, CancellationToken cancellationToken)
the same

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Program.cs
> +//using InternetShop;
delete commited code

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
>          public async Task<UserViewModel?> Update([FromBody] UserEntity userEntity, CancellationToken cancellationToken)
And add Id as a parameter

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
>              List<UserViewModel> userViewModels = new List<UserViewModel>();
It's not necessary

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
>              }
See how we can use IEnumerable with autoMapper

2023-04-07 07:48 UTC, Blackolf931 commented on InternetShop/BLL/Services/UserService.cs
>              }
See how we can use IEnumerable with autoMapper

2023-04-07 08:09 UTC, polashkind commented on InternetShop/InternetShop/Program.cs
> +//using InternetShop;
Done

2023-04-10 08:22 UTC, Blackolf931 approved these changes

2023-04-10 08:38 UTC, merged