Feature/database connect
polashkind/InternetShop pull request #7
Opened 2023-03-30 11:24 UTC by polashkind

2023-03-30 11:34 UTC, Blackolf931 requested changes

2023-03-30 11:34 UTC, Blackolf931 commented on InternetShop/DAL/Context/DatabaseContext.cs
> +        {
Посмотри, как у тебя делается форматирование документа, нужно для выравнивания строк

2023-03-30 11:34 UTC, Blackolf931 commented on InternetShop/DAL/Repositories/IRepositoryBase.cs
> +}
delete unneсessary files

2023-03-30 11:34 UTC, Blackolf931 commented on InternetShop/InternetShop/Controllers/UserController.cs
> +        //}
delete commited code

2023-03-30 11:39 UTC, polashkind commented on InternetShop/DAL/Context/DatabaseContext.cs
> +        {
done

2023-03-30 11:44 UTC, polashkind commented on InternetShop/InternetShop/Controllers/UserController.cs
> +        //}
done

2023-04-03 09:43 UTC, Blackolf931 approved these changes

2023-04-03 09:44 UTC, Blackolf931 approved these changes

2023-04-03 09:47 UTC, merged